// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVigh0fl25pjHU99rh_0U6-YYJ6Db3ndw',
    appId: '1:845387116350:web:a6dbe3a4d6cd399fb4466f',
    messagingSenderId: '845387116350',
    projectId: 'real-estate-600f3',
    authDomain: 'real-estate-600f3.firebaseapp.com',
    storageBucket: 'real-estate-600f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6J8b-LNKU6_K7bjKbx14OFMcX_BVgSds',
    appId: '1:845387116350:android:f69416d3abeeab80b4466f',
    messagingSenderId: '845387116350',
    projectId: 'real-estate-600f3',
    storageBucket: 'real-estate-600f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdsn_XvmQn9SYoNg5oblELySC1PnqF9Zo',
    appId: '1:845387116350:ios:c2f42b2641500c4ab4466f',
    messagingSenderId: '845387116350',
    projectId: 'real-estate-600f3',
    storageBucket: 'real-estate-600f3.firebasestorage.app',
    iosBundleId: 'com.example.estate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdsn_XvmQn9SYoNg5oblELySC1PnqF9Zo',
    appId: '1:845387116350:ios:c2f42b2641500c4ab4466f',
    messagingSenderId: '845387116350',
    projectId: 'real-estate-600f3',
    storageBucket: 'real-estate-600f3.firebasestorage.app',
    iosBundleId: 'com.example.estate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVigh0fl25pjHU99rh_0U6-YYJ6Db3ndw',
    appId: '1:845387116350:web:1cd1706662e6a8bab4466f',
    messagingSenderId: '845387116350',
    projectId: 'real-estate-600f3',
    authDomain: 'real-estate-600f3.firebaseapp.com',
    storageBucket: 'real-estate-600f3.firebasestorage.app',
  );
}
